### ISSUE TITLE
不能开radial吗？打开编译会报错

### ISSUE THREAD

**Issue by jeromeli002** [zhaqian12/qmk_firmware#14]
不能开radial吗？打开编译会报错
![image](https://user-images.githubusercontent.com/5648129/179876730-31cb58f1-846c-45a9-9943-0f1283afd229.png)

**Comment by zhaqian12** [comment]
请使用zq-linux分支，qmk-zq是测试分支。

**Comment by zhaqian12** [comment]
请在本fork仓库里找，非qmk官方仓库
