### ISSUE TITLE
有vial-qmk改openrgb和radial这些功能的计划吗？

### ISSUE THREAD

**Issue by jeromeli002** [zhaqian12/qmk_firmware#16]
有vial+openrgb和radial这些功能的计划吗？vial可以直接识别 不用手动导入json方便不少，zhaqian里面的zqlib库可以是能直接丢进qmk能用还是需要改其他地方才行？

**Comment by zhaqian12** [comment]
自行添加即可，zqlib仅存放代码。vial和qmk原仓库添加没有区别。

**Comment by jeromeli002** [comment]
> 

好的谢谢 试着加vial试试行不行

**Comment by jeromeli002** [comment]
> 自行添加即可，zqlib仅存放代码。vial和qmk原仓库添加没有区别。

试了下 好像不行，放qmk可以使用，放vial-qmk不能用…………小白不知道还要改那些地方了…………
