### ISSUE TITLE
Missing commit in chibios-contrib

### ISSUE THREAD

**Issue by thxph** [zhaqian12/qmk_firmware#17]
hello, it seems the current commit in the submodule lib/chibios-contrib (eafdffab68547b9c18914f8b33cd7be67fc1fdd2) is not pushed anywhere, making a `git clone` and `git submodule update` fail. Could you please push these commits to your chibios-contrib fork and change the submodule path to your fork.
Thanks 😄

**Comment by zhaqian12** [comment]
Sorry, please look at this [issue](https://github.com/zhaqian12/ZQ-Keyboard/issues/1#issuecomment-1172867922)

**Comment by zhaqian12** [comment]
fixed
