### ISSUE TITLE
Microsoft Dial 还不完善吗？PS里面你不能挑笔刷？

### ISSUE THREAD

**Issue by jeromeli002** [zhaqian12/qmk_firmware#26]
Microsoft Dial 还不完善吗？PS里面你不能挑笔刷？和外面调出来的差不多
正常情况应该是ps界面里面弹出的又笔刷菜单吗
![(ZVRTCQGVJJSEVQ`HQX3CC4](https://user-images.githubusercontent.com/5648129/184103106-4c7029a5-b0c6-440e-8e7b-92357036c3dd.png)
![9)U5)43HS9DF3RQ7ISHW`8S](https://user-images.githubusercontent.com/5648129/184103128-beb54c11-aa7f-4fce-b198-97b110b825d5.png)

**Comment by zhaqian12** [comment]
你应该确定你的软件是否支持radial交互。仓库的radialcontroller根据windows提高的hid 描述符实现，阉割了触觉反馈。如果你有需要完善的地方欢迎提出pr。

**Comment by jeromeli002** [comment]
> 你应该确定你的软件是否支持radial交互。仓库的radialcontroller根据windows提高的hid 描述符实现，阉割了触觉反馈。如果你有需要完善的地方欢迎提出pr。

最新版的Photoshop 官网介绍是支持radial的，但是换电脑还是没有笔刷选项出来 难道是因为盗版的原因不支持？？
