### ISSUE TITLE
关于在ZF中提到的stm32f103uf2.ld文件

### ISSUE THREAD

**Issue by Mokuvita** [zhaqian12/qmk_firmware#31]
你好，在zf中提到的[stm32f103xb_uf2.ld](https://github.com/zhaqian12/qmk_firmware/blob/master/platforms/chibios/boards/STM32_F103_STM32DUINO/ld/STM32F103xB_uf2.ld) 的文件没了，能否再提供下

**Comment by zhaqian12** [comment]
https://github.com/zhaqian12/qmk_firmware/tree/zhaqian/platforms/chibios/boards/STM32_F103_STM32DUINO/ld

**Comment by Mokuvita** [comment]
> https://github.com/zhaqian12/qmk_firmware/tree/zhaqian/platforms/chibios/boards/STM32_F103_STM32DUINO/ld

谢谢
