### ISSUE TITLE
[Bug] AT32F413xx compile error

### ISSUE THREAD

**Issue by nkwllm** [zhaqian12/qmk_firmware#80]
### Describe the Bug

Compiling: lib/chibios-contrib/os/hal/ports/AT32/AT32F413xx/hal_lld.c                              In file included from keyboards/zhaqian/zq50/at32f413/mcuconf.h:19,
                 from ./platforms/chibios/boards/common/configs/halconf.h:34,
                 from keyboards/zhaqian/zq50/at32f413/halconf.h:21,
                 from ./lib/chibios/os/hal/include/hal.h:32,
                 from ./platforms/chibios/drivers/wear_leveling/wear_leveling_efl_config.h:6,
                 from <command-line>:
lib/chibios-contrib/os/hal/ports/AT32/AT32F413xx/hal_lld.c: In function 'hal_lld_backup_domain_init':
./platforms/chibios/boards/GENERIC_AT32_F413/configs/mcuconf.h:55:44: error: 'AT32_RTCSEL_LSI' undeclared (first use in this function); did you mean 'AT32_RTCSEL_LICK'?
   55 | #define AT32_RTCSEL                        AT32_RTCSEL_LSI
      |                                            ^~~~~~~~~~~~~~~
lib/chibios-contrib/os/hal/ports/AT32/AT32F413xx/hal_lld.c:60:41: note: in expansion of macro 'AT32_RTCSEL'
   60 |   if ((CRM->BPDC & AT32_RTCSEL_MASK) != AT32_RTCSEL) {
      |                                         ^~~~~~~~~~~
./platforms/chibios/boards/GENERIC_AT32_F413/configs/mcuconf.h:55:44: note: each undeclared identifier is reported only once for each function it appears in
   55 | #define AT32_RTCSEL                        AT32_RTCSEL_LSI
      |                                            ^~~~~~~~~~~~~~~
lib/chibios-contrib/os/hal/ports/AT32/AT32F413xx/hal_lld.c:60:41: note: in expansion of macro 'AT32_RTCSEL'
   60 |   if ((CRM->BPDC & AT32_RTCSEL_MASK) != AT32_RTCSEL) {
      |                                         ^~~~~~~~~~~
 [ERRORS]
 |
 |
 |
make[1]: *** [builddefs/common_rules.mk:361：.build/obj_zhaqian_zq50_at32f413_via/./lib/chibios-contrib/os/hal/ports/AT32/AT32F413xx/hal_ lld.o] 错误 1
Make finished with errors
make: *** [Makefile:392：zhaqian/zq50/at32f413:via] 错误 1

### Keyboard Used

qmk compile -kb zhaqian/zq50/at32f413 -km default

### Operating System

win 10

### qmk doctor Output

```text
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.1
Ψ QMK home: C:/QMK/qmk_firmware
Ψ Detected Windows 10 (10.0.17763).
Ψ QMK MSYS version: 1.7.2
Ψ Git branch: master
Ψ Repo version: 0.14.16
⚠ Git has unstashed/uncommitted changes.
⚠ The official repository does not seem to be configured as git remote "upstream".
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 10.1.0
Ψ Found avr-gcc version 8.5.0
Ψ Found avrdude version 7.0
Ψ Found dfu-programmer version 0.7.2
Ψ Found dfu-util version 0.11
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2023-04-15 13:48:04 +0000 --  (11edb1610)
Ψ - lib/chibios-contrib: 2023-07-17 11:39:05 +0200 --  (da78eb37)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/pico-sdk: 2023-02-12 20:19:37 +0100 --  (a3398d8)
Ψ - lib/lvgl: 2022-04-11 04:44:53 -0600 --  (e19410f8)
Ψ QMK is ready to go, but minor problems were found
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by zhaqian12** [comment]
fix
