### ISSUE TITLE
[Bug] S75编译错误/logorgb作为指示灯无反应

### ISSUE THREAD

**Issue by Solodros** [zhaqian12/qmk_firmware#81]
### Describe the Bug

第一个bug是使用你的分支直接编译S75，无法成功。zq50系列可以编译成功；
第二个bug是添加logorgb，对应的灯珠类型为8，via里增加相关设置；全局灯光里能正常开关logo灯，但是指示灯里选择logo灯则没有反应

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by zhaqian12** [comment]
1.FIX
2.没问题
