### ISSUE TITLE
[Bug] 无法在AT32F405上开启PS2功能

### ISSUE THREAD

**Issue by Solodros** [zhaqian12/qmk_firmware#89]
### Describe the Bug

根据qmk文档[https://docs.qmk.fm/#/reference_info_json?id=info-json-reference](url)和[https://docs.qmk.fm/#/feature_ps2_mouse](url)在zq50/info.json添加PS2设备相关设置
![image](https://github.com/zhaqian12/qmk_firmware/assets/34903426/a7c78e46-ac26-4251-b550-d381f12c06bc)
在zq50/at32f405/halconf.h添加#define PAL_USE_CALLBACKS TRUE
后编译不通过，报错信息如下。（相同设置在STM32F401编译通过且工作正常）

### Operating System

win10

### qmk doctor Output

```text
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.2
Ψ QMK home: E:/zqQMK
Ψ Detected Windows 10 (10.0.19045).
Ψ QMK MSYS version: 1.7.2
Ψ Git branch: zhaqian
Ψ Repo version: 0.22.5
⚠ Git has unstashed/uncommitted changes.
⚠ The official repository does not seem to be configured as git remote "upstream".
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Additional Context

QMK Firmware 0.22.5
Making zhaqian/zq50/at32f405 with keymap via

arm-none-eabi-gcc.exe (GCC) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO 
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Generating: .build/obj_zhaqian_zq50_at32f405_via/src/default_keyboard.h                             [OK]
Generating: .build/obj_zhaqian_zq50_at32f405_via/src/info_config.h                                  [OK]
Generating: .build/obj_zhaqian_zq50_at32f405_via/src/default_keyboard.c                             [OK]
Compiling: .build/obj_zhaqian_zq50_at32f405_via/src/default_keyboard.c                              [OK]
Compiling: quantum/keymap_introspection.c                                                           [OK]
Compiling: keyboards/zhaqian/zq50/zq50.c                                                            [OK]
Compiling: quantum/led.c                                                                            [OK]
Compiling: quantum/bitwise.c                                                                        [OK]
Compiling: quantum/quantum.c                                                                        [OK]
Compiling: quantum/action_layer.c                                                                   [OK]
Compiling: quantum/eeconfig.c                                                                       [OK]
Compiling: quantum/action.c                                                                         [OK]
Compiling: quantum/action_tapping.c                                                                 [OK]
Compiling: quantum/keyboard.c                                                                       [OK]
Compiling: quantum/sync_timer.c                                                                     [OK]
Compiling: quantum/action_util.c                                                                    [OK]
Compiling: quantum/keymap_common.c                                                                  [OK]
Compiling: quantum/keycode_config.c                                                                 [OK]
Compiling: quantum/logging/sendchar.c                                                               [OK]
Compiling: quantum/logging/debug.c                                                                  [OK]
Compiling: quantum/logging/print.c                                                                  [OK]
Compiling: quantum/bootmagic/bootmagic_lite.c                                                       [OK]
Compiling: quantum/matrix_common.c                                                                  [OK]
Compiling: quantum/bootmagic/magic.c                                                                [OK]
Compiling: quantum/matrix.c                                                                         [OK]
Compiling: quantum/main.c                                                                           [OK]
Compiling: lib/printf/src/printf/printf.c                                                           [OK]
Compiling: quantum/debounce/sym_defer_g.c                                                           [OK]
Compiling: quantum/mousekey.c                                                                       [OK]
Compiling: drivers/eeprom/eeprom_driver.c                                                           [OK]
Compiling: drivers/eeprom/eeprom_wear_leveling.c                                                    [OK]
Compiling: quantum/wear_leveling/wear_leveling.c                                                    [OK]
Compiling: quantum/color.c                                                                          [OK]
Compiling: lib/lib8tion/lib8tion.c                                                                  [OK]
Compiling: quantum/rgb_matrix/rgb_matrix_drivers.c                                                  [OK]
Compiling: platforms/chibios/drivers/wear_leveling/wear_leveling_efl.c                              [OK]
Compiling: quantum/process_keycode/process_rgb.c                                                    [OK]
Compiling: platforms/chibios/drivers/ws2812_pwm.c                                                   [OK]
Compiling: quantum/led_tables.c                                                                     [OK]
Compiling: quantum/rgb_matrix/rgb_matrix.c                                                          [OK]
Compiling: lib/fnv/qmk_fnv_type_validation.c                                                        [OK]
Compiling: quantum/via.c                                                                            [OK]
Compiling: quantum/process_keycode/process_magic.c                                                  [OK]
Compiling: lib/fnv/hash_64a.c                                                                       [OK]
Compiling: lib/fnv/hash_32a.c                                                                       [OK]
Compiling: quantum/send_string/send_string.c                                                        [OK]
Compiling: platforms/chibios/drivers/ps2/ps2_io.c                                                   [OK]
Compiling: drivers/ps2/ps2_mouse.c                                                                  [OK]
Compiling: quantum/process_keycode/process_auto_shift.c                                             [OK]
Compiling: drivers/ps2/ps2_interrupt.c                                                              [OK]
Compiling: quantum/encoder.c                                                                        [OK]
Compiling: quantum/os_detection.c                                                                   [OK]
Compiling: quantum/radial_controller.c                                                              [OK]
Compiling: quantum/auto_switch_layers.c                                                             [OK]
Compiling: quantum/rgb_matrix/rgb_matrix_control.c                                                  [OK]
Compiling: quantum/rgb_matrix/underglow_rgb_matrix.c                                                [OK]
Compiling: quantum/rgb_matrix/signalrgb.c                                                           [OK]
Compiling: quantum/rgb_matrix/openrgb.c                                                             [OK]
Compiling: quantum/hidrgb_protocol.c                                                                [OK]
Compiling: quantum/rgb_matrix/dynamic_rgb_indicators.c                                              [OK]
Compiling: quantum/via_custom_keycode.c                                                             [OK]
Compiling: quantum/dynamic_tap_dance.c                                                              [OK]
Compiling: quantum/magic_settings.c                                                                 [OK]
Compiling: quantum/via_custom_control.c                                                             [OK]
Compiling: quantum/dynamic_combos.c                                                                 [OK]
Compiling: quantum/process_keycode/process_combo.c                                                  [OK]
Compiling: quantum/process_keycode/process_grave_esc.c                                              [OK]
Compiling: quantum/process_keycode/process_tri_layer.c                                              [OK]
Compiling: quantum/dynamic_keymap.c                                                                 [OK]
Compiling: quantum/tri_layer.c                                                                      [OK]
Compiling: quantum/process_keycode/process_space_cadet.c                                            [OK]
Compiling: quantum/process_keycode/process_tap_dance.c                                              [OK]
Compiling: tmk_core/protocol/host.c                                                                 [OK]
Compiling: tmk_core/protocol/report.c                                                               [OK]
Compiling: platforms/chibios/hardware_id.c                                                          [OK]
Compiling: tmk_core/protocol/usb_util.c                                                             [OK]
Compiling: platforms/synchronization_util.c                                                         [OK]
Compiling: platforms/suspend.c                                                                      [OK]
Compiling: platforms/timer.c                                                                        [OK]
Compiling: tmk_core/protocol/usb_device_state.c                                                     [OK]
Compiling: platforms/chibios/suspend.c                                                              [OK]
Compiling: platforms/chibios/platform.c                                                             [OK]
Assembling: lib/chibios/os/common/startup/ARMCMx/compilers/GCC/crt0_v7m.S                           [OK]
Assembling: lib/chibios/os/common/startup/ARMCMx/compilers/GCC/vectors.S                            [OK]
Compiling: platforms/chibios/bootloaders/tinyuf2.c                                                  [OK]
Assembling: lib/chibios/os/common/ports/ARMv7-M/compilers/GCC/chcoreasm.S                           [OK]
Compiling: platforms/chibios/timer.c                                                                [OK]
Compiling: tmk_core/protocol/usb_descriptor.c                                                       [OK]
Compiling: tmk_core/protocol/chibios/chibios.c                                                      [OK]
Compiling: tmk_core/protocol/chibios/usb_main.c                                                     [OK]
Compiling: tmk_core/protocol/chibios/usb_driver.c                                                   [OK]
Compiling: tmk_core/protocol/chibios/usb_util.c                                                     [OK]
Compiling: lib/chibios/os/oslib/src/chmboxes.c                                                      [OK]
Compiling: lib/chibios/os/oslib/src/chmemheaps.c                                                    [OK]
Compiling: lib/chibios/os/oslib/src/chmempools.c                                                    [OK]
Compiling: lib/chibios/os/oslib/src/chmemcore.c                                                     [OK]
Compiling: lib/chibios/os/oslib/src/chpipes.c                                                       [OK]
Compiling: lib/chibios/os/oslib/src/chdelegates.c                                                   [OK]
Compiling: lib/chibios/os/oslib/src/chobjcaches.c                                                   [OK]
Compiling: lib/chibios/os/oslib/src/chfactory.c                                                     [OK]
Compiling: lib/chibios/os/common/startup/ARMCMx/compilers/GCC/crt1.c                                [OK]
Compiling: lib/chibios/os/rt/src/chdebug.c                                                          [OK]
Compiling: lib/chibios/os/rt/src/chtrace.c                                                          [OK]
Compiling: lib/chibios/os/rt/src/chsys.c                                                            [OK]
Compiling: lib/chibios/os/rt/src/chrfcu.c                                                           [OK]
Compiling: lib/chibios/os/rt/src/chtm.c                                                             [OK]
Compiling: lib/chibios/os/rt/src/chschd.c                                                           [OK]
Compiling: lib/chibios/os/rt/src/chthreads.c                                                        [OK]
Compiling: lib/chibios/os/rt/src/chvt.c                                                             [OK]
Compiling: lib/chibios/os/rt/src/chinstances.c                                                      [OK]
Compiling: lib/chibios/os/rt/src/chstats.c                                                          [OK]
Compiling: lib/chibios/os/rt/src/chregistry.c                                                       [OK]
Compiling: lib/chibios/os/rt/src/chcond.c                                                           [OK]
Compiling: lib/chibios/os/rt/src/chsem.c                                                            [OK]
Compiling: lib/chibios/os/rt/src/chevents.c                                                         [OK]
Compiling: lib/chibios/os/rt/src/chmtx.c                                                            [OK]
Compiling: lib/chibios/os/rt/src/chmsg.c                                                            [OK]
Compiling: lib/chibios/os/hal/osal/rt-nil/osal.c                                                    [OK]
Compiling: lib/chibios/os/common/ports/ARMv7-M/chcore.c                                             [OK]
Compiling: lib/chibios/os/rt/src/chdynamic.c                                                        [OK]
Compiling: lib/chibios/os/hal/src/hal_st.c                                                          [OK]
Compiling: lib/chibios/os/hal/src/hal.c                                                             [OK]
Compiling: lib/chibios/os/hal/src/hal_buffers.c                                                     [OK]
Compiling: lib/chibios/os/hal/src/hal_flash.c                                                       [OK]
Compiling: lib/chibios/os/hal/src/hal_adc.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_can.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_queues.c                                                      [OK]
Compiling: lib/chibios/os/hal/src/hal_mmcsd.c                                                       [OK]
Compiling: lib/chibios/os/hal/src/hal_dac.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_crypto.c                                                      [OK]
Compiling: lib/chibios/os/hal/src/hal_efl.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_gpt.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_i2c.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_i2s.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_icu.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_mmc_spi.c                                                     [OK]
Compiling: lib/chibios/os/hal/src/hal_mac.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_pal.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_pwm.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_rtc.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_sdc.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_serial.c                                                      [OK]
Compiling: lib/chibios/os/hal/src/hal_sio.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_serial_usb.c                                                  [OK]
Compiling: lib/chibios/os/hal/src/hal_trng.c                                                        [OK]
Compiling: lib/chibios/os/hal/src/hal_wdg.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_spi.c                                                         [OK]
Compiling: lib/chibios/os/hal/src/hal_wspi.c                                                        [OK]
Compiling: lib/chibios/os/hal/src/hal_uart.c                                                        [OK]
Compiling: platforms/chibios/boards/GENERIC_AT32_F405/board/board.c                                 [OK]
Compiling: lib/chibios/os/hal/src/hal_usb.c                                                         [OK]
Compiling: lib/chibios/os/hal/lib/streams/chprintf.c                                                [OK]
Compiling: lib/chibios/os/hal/lib/streams/chscanf.c                                                 [OK]
Compiling: lib/chibios/os/hal/lib/streams/memstreams.c                                              [OK]
Compiling: lib/chibios/os/hal/lib/streams/nullstreams.c                                             [OK]
Compiling: lib/chibios/os/hal/lib/streams/bufstreams.c                                              [OK]
Compiling: lib/chibios/os/various/syscalls.c                                                        [OK]
Compiling: platforms/chibios/wait.c                                                                 [OK]
Compiling: platforms/chibios/syscall-fallbacks.c                                                    [OK]
Compiling: lib/chibios/os/hal/ports/common/ARMCMx/nvic.c                                            [OK]
Compiling: lib/chibios-contrib/os/hal/ports/AT32/AT32F402_5xx/hal_lld.c                             [OK]
Compiling: platforms/chibios/synchronization_util.c                                                 [OK]
Compiling: lib/chibios-contrib/os/hal/ports/AT32/AT32F402_5xx/at32_isr.c                           In file included from ./lib/chibios/os/rt/include/chport.h:37,
                 from ./lib/chibios/os/rt/include/ch.h:106,
                 from ./lib/chibios/os/hal/osal/rt-nil/osal.h:32,
                 from ./lib/chibios/os/hal/include/hal.h:30,
                 from ./platforms/chibios/drivers/wear_leveling/wear_leveling_efl_config.h:6,
                 from <command-line>:
./lib/chibios-contrib/os/hal/ports/AT32/AT32F402_5xx/at32_isr.h:130:44: error: redefinition of 'VectorE8'
  130 | #define AT32_EXINT21_HANDLER               VectorE8    /* ERTC TAMP        */
      |                                            ^~~~~~~~
./lib/chibios/os/common/ports/ARMv7-M/chcore.h:680:37: note: in definition of macro 'PORT_IRQ_HANDLER'
  680 |   #define PORT_IRQ_HANDLER(id) void id(void)
      |                                     ^~
./lib/chibios/os/hal/osal/rt-nil/osal.h:323:30: note: in expansion of macro 'CH_IRQ_HANDLER'
  323 | #define OSAL_IRQ_HANDLER(id) CH_IRQ_HANDLER(id)
      |                              ^~~~~~~~~~~~~~
lib/chibios-contrib/os/hal/ports/AT32/AT32F402_5xx/at32_isr.c:291:1: note: in expansion of macro 'OSAL_IRQ_HANDLER'
  291 | OSAL_IRQ_HANDLER(AT32_EXINT21_HANDLER) {
      | ^~~~~~~~~~~~~~~~
lib/chibios-contrib/os/hal/ports/AT32/AT32F402_5xx/at32_isr.c:291:18: note: in expansion of macro 'AT32_EXINT21_HANDLER'
  291 | OSAL_IRQ_HANDLER(AT32_EXINT21_HANDLER) {
      |                  ^~~~~~~~~~~~~~~~~~~~
./lib/chibios-contrib/os/hal/ports/AT32/AT32F402_5xx/at32_isr.h:128:44: note: previous definition of 'VectorE8' with type 'void(void)'  128 | #define AT32_EXINT18_HANDLER               VectorE8    /* OTGFS1 WAKEUP    */
      |                                            ^~~~~~~~
./lib/chibios/os/common/ports/ARMv7-M/chcore.h:680:37: note: in definition of macro 'PORT_IRQ_HANDLER'
  680 |   #define PORT_IRQ_HANDLER(id) void id(void)
      |                                     ^~
./lib/chibios/os/hal/osal/rt-nil/osal.h:323:30: note: in expansion of macro 'CH_IRQ_HANDLER'
  323 | #define OSAL_IRQ_HANDLER(id) CH_IRQ_HANDLER(id)
      |                              ^~~~~~~~~~~~~~
lib/chibios-contrib/os/hal/ports/AT32/AT32F402_5xx/at32_isr.c:250:1: note: in expansion of macro 'OSAL_IRQ_HANDLER'
  250 | OSAL_IRQ_HANDLER(AT32_EXINT18_HANDLER) {
      | ^~~~~~~~~~~~~~~~
lib/chibios-contrib/os/hal/ports/AT32/AT32F402_5xx/at32_isr.c:250:18: note: in expansion of macro 'AT32_EXINT18_HANDLER'
  250 | OSAL_IRQ_HANDLER(AT32_EXINT18_HANDLER) {
      |                  ^~~~~~~~~~~~~~~~~~~~
 [ERRORS]
 |
 |
 |
make[1]: *** [builddefs/common_rules.mk:361：.build/obj_zhaqian_zq50_at32f405_via/./lib/chibios-contrib/os/hal/ports/AT32/AT32F402_5xx/at32_isr.o] 错误 1
make[1]: *** 正在等待未完成的任务....
Compiling: lib/chibios-contrib/os/hal/ports/AT32/AT32F402_5xx/hal_efl_lld.c                         [OK]
Compiling: lib/chibios-contrib/os/hal/ports/AT32/LLD/GPIOv2/hal_pal_lld.c                           [OK]
Compiling: lib/chibios-contrib/os/hal/ports/AT32/LLD/DMAv2/at32_dma.c                               [OK]
Compiling: lib/chibios-contrib/os/hal/ports/AT32/LLD/TMRv1/hal_gpt_lld.c                            [OK]
Compiling: lib/chibios-contrib/os/hal/ports/AT32/LLD/TMRv1/hal_icu_lld.c                            [OK]
Compiling: lib/chibios-contrib/os/hal/ports/AT32/LLD/TMRv1/hal_pwm_lld.c                            [OK]
Compiling: lib/chibios-contrib/os/hal/ports/AT32/LLD/SYSTICKv1/hal_st_lld.c                         [OK]
Compiling: lib/chibios-contrib/os/hal/ports/AT32/LLD/USARTv1/hal_serial_lld.c                       [OK]
Compiling: lib/chibios-contrib/os/hal/ports/AT32/LLD/USARTv1/hal_uart_lld.c                         [OK]
Compiling: lib/chibios-contrib/os/hal/ports/AT32/LLD/I2Cv2/hal_i2c_lld.c                            [OK]
Compiling: lib/chibios-contrib/os/hal/ports/AT32/LLD/ADCv2/hal_adc_lld.c                            [OK]
Compiling: lib/chibios-contrib/os/hal/ports/AT32/LLD/SPIv1/hal_i2s_lld.c                            [OK]
Compiling: lib/chibios-contrib/os/hal/ports/AT32/LLD/SPIv1/hal_spi_v2_lld.c                         [OK]
Compiling: lib/chibios-contrib/os/hal/ports/AT32/LLD/OTGv1/hal_usb_lld.c                            [OK]
Make finished with errors

**Comment by zhaqian12** [comment]
This is typo, you can correct the vector number yourself first.

**Comment by Solodros** [comment]
感谢，修正之后编译成功
