### ISSUE TITLE
[Bug] rgb_matrix.c似乎有逻辑错误

### ISSUE THREAD

**Issue by Solodros** [zhaqian12/qmk_firmware#97]
### Describe the Bug

zhaqian分支的[rgb_matrix.c](https://github.com/zhaqian12/qmk_firmware/blob/zhaqian/quantum/rgb_matrix/rgb_matrix.c)第445-454行似乎有错误，导致383行的static void rgb_task_render(uint8_t effect) {出现缺少“}"的提示。
![image](https://github.com/zhaqian12/qmk_firmware/assets/34903426/efc7b4e5-f242-4ddc-a374-11864fc289aa)
![image](https://github.com/zhaqian12/qmk_firmware/assets/34903426/86bed8a9-34f5-4cf3-83d4-b79e723f4e81)

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by zhaqian12** [comment]
你好，没有发现问题。
